import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { CreateProject } from "../pages/CreateProject";
import { Dashboard } from "../pages/Dashboard";
import { ExtractionReview } from "../pages/ExtractionReview";
import { Landing } from "../pages/Landing";
import { Projects } from "../pages/Projects";

function wrap(ui: React.ReactNode, path = "/") {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } });
  return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}>{ui}</MemoryRouter></QueryClientProvider>);
}

afterEach(() => vi.restoreAllMocks());

test("landing page and accessible timeline render", () => {
  wrap(<Landing />);
  expect(screen.getByRole("heading", { name: /see your film/i })).toBeInTheDocument();
  expect(screen.getByRole("region", { name: /audience mind timeline/i })).toBeInTheDocument();
  expect(screen.getByText(/not generated by gemini/i)).toBeInTheDocument();
});

test("create project validates required fields", async () => {
  wrap(<CreateProject />);
  await userEvent.click(screen.getByRole("button", { name: "Create Project" }));
  expect(await screen.findByText("Film title is required")).toBeInTheDocument();
  expect(screen.getByText("Genre is required")).toBeInTheDocument();
});

test("projects empty state renders", async () => {
  vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({ items: [], page: 1, page_size: 20, total: 0 })));
  wrap(<Projects />);
  expect(await screen.findByText(/cutting room is quiet/i)).toBeInTheDocument();
});

test("project card renders", async () => {
  vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({ items: [{ id: "p1", owner_id: "u", title: "The Red Key", genre: "Mystery", intended_audience: "Adults", target_duration_seconds: 240, description: "Synthetic film", status: "draft", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z", versions: [] }], page: 1, page_size: 20, total: 1 })));
  wrap(<Projects />);
  expect(await screen.findByRole("heading", { name: "The Red Key" })).toBeInTheDocument();
});

test("API error state renders", async () => {
  vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({ error: { message: "down" } }), { status: 503 }));
  wrap(<Projects />);
  expect(await screen.findByRole("alert")).toHaveTextContent(/could not load/i);
});

test("project dashboard and readiness render", async () => {
  vi.spyOn(globalThis, "fetch").mockImplementation(async (input) => {
    const url = String(input);
    if (url.includes("readiness")) return new Response(JSON.stringify({ services: { api: { status: "ready", detail: "API process is responding" } } }));
    if (url.includes("activity")) return new Response(JSON.stringify({ items: [], page: 1, page_size: 20, total: 0 }));
    return new Response(JSON.stringify({ id: "p1", owner_id: "u", title: "The Red Key", genre: "Mystery", intended_audience: "Adults", target_duration_seconds: 240, description: "Synthetic film", status: "draft", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z", versions: [] }));
  });
  wrap(<Routes><Route path="/projects/:id" element={<Dashboard />} /></Routes>, "/projects/p1");
  expect(await screen.findByRole("heading", { name: "The Red Key" })).toBeInTheDocument();
  expect(await screen.findByText("ready")).toBeInTheDocument();
  expect(screen.getByRole("button", { name: /run audience analysis/i })).toBeDisabled();
});

test("extraction upload workspace enforces prerequisites", async () => {
  vi.spyOn(globalThis, "fetch").mockImplementation(async (input) => {
    const url = String(input);
    if (url.endsWith("/uploads")) return new Response(JSON.stringify([]));
    if (url.endsWith("/extraction")) return new Response(JSON.stringify({ error: { message: "not found" } }), { status: 404 });
    return new Response(JSON.stringify({ id: "p1", title: "The Red Key", versions: [{ id: "v1", label: "Cut A" }] }));
  });
  wrap(<Routes><Route path="/projects/:id/versions/:versionId/extraction" element={<ExtractionReview />} /></Routes>, "/projects/p1/versions/v1/extraction");
  expect(await screen.findByRole("heading", { name: "Extraction review" })).toBeInTheDocument();
  expect(screen.getByLabelText(/choose screenplay pdf/i)).toHaveAttribute("accept", "application/pdf");
  expect(screen.getByRole("button", { name: /create extraction draft/i })).toBeDisabled();
});

test("approved extraction renders provenance and locked review", async () => {
  const extraction = { id: "e1", job_id: "j1", version_id: "v1", job_status: "completed", provider: "local_fixture", model_name: null, review_status: "approved", created_at: "2026-08-01T00:00:00Z", updated_at: "2026-08-01T00:00:00Z", content: { scenes: [{ id: "SC-001", scene_number: 1, heading: "ARRIVAL", summary: "Maya arrives", start_ms: 0, end_ms: 1000, character_ids: ["CHAR-001"] }], characters: [{ id: "CHAR-001", name: "Maya", description: "Lead" }], story_facts: [{ id: "FACT-001", statement: "Maya has a key", fact_type: "prop", introduced_scene_id: "SC-001", payoff_scene_id: null }], evidence: [{ id: "EV-001", timestamp_ms: 0, event_type: "visual", summary: "Red key", confidence: 0.8 }], limitations: ["Human-reviewed fixture"] } };
  vi.spyOn(globalThis, "fetch").mockImplementation(async (input) => {
    const url = String(input);
    if (url.endsWith("/uploads")) return new Response(JSON.stringify([{ id: "a1", kind: "script", original_name: "film.pdf" }, { id: "a2", kind: "video", original_name: "film.mp4" }]));
    if (url.endsWith("/extraction")) return new Response(JSON.stringify(extraction));
    return new Response(JSON.stringify({ id: "p1", title: "The Red Key", versions: [{ id: "v1", label: "Cut A" }] }));
  });
  wrap(<Routes><Route path="/projects/:id/versions/:versionId/extraction" element={<ExtractionReview />} /></Routes>, "/projects/p1/versions/v1/extraction");
  expect(await screen.findByText(/local_fixture · approved/i)).toBeInTheDocument();
  expect(screen.getByDisplayValue("Maya")).toBeDisabled();
  expect(screen.getByText(/approved and locked/i)).toBeInTheDocument();
});
