from app.core.repository import get_repository
from app.services.knowledge_graph_service import knowledge_graph

def seed_booxclash(workspace_id:str,reset:bool=True)->dict:
    repo=get_repository()
    if reset:repo.clear_workspace(workspace_id)
    repo.create("workspaces",workspace_id,{"id":workspace_id,"name":"Kondai Demo Workspace","owner":"demo-founder"});repo.create("members",workspace_id,{"id":"demo-founder","role":"owner"})
    product=repo.create("products",workspace_id,{"name":"BooxClash","description":"An AI-native education platform helping teachers create planning, assessment and student-learning workflows while supporting schools.","url":"https://booxclash.com","category":"Education SaaS","stage":"early_revenue","pricing":"Individual and school subscriptions","target_customer":"Teachers and schools","primary_goal":"Convert teacher clusters into school plans, reduce churn and improve activation."})
    snapshots=[("billing","BooxClash billing snapshot",{"currency":"ZMW","mrr":290,"arr":3480,"active_paying_schools":2,"school_target":100,"individual_churn_30d":53.8,"individual_retention":22.6,"revenue_at_risk":90,"active_customers":9,"revenue":2320}),("analytics","BooxClash product analytics",{"paid_individual_activation":0,"school_activation":0,"documents_last_30_days":0,"dormant_paid_users":7,"usage_growth_30d":0,"feature_usage":{"Schemes of work":0,"Lesson plans":0,"Assessments":0,"BooxRoom challenges":2},"journeys":{"Paid → first document":0,"Teacher cluster → school plan":4}}),("github","BooxClash GitHub snapshot",{"repository":"booxclash","recent_commits":48,"open_bugs":6,"recent_features":["BooxRoom secure assessment engine","Manual moderation","Topic remediation","Guided tutor","Growth command centre"],"critical_issues":["Generation events are not consistently linked to analytics."]}),("support","BooxClash support snapshot",{"open_tickets":5,"satisfaction":72,"themes":[{"name":"First-week onboarding difficulty","count":7},{"name":"Renewal and pricing questions","count":5},{"name":"Teachers need workflow guidance","count":6}],"feature_requests":["Direct workflow links","Simpler school onboarding","Clearer usage reporting"]}),("competitor","Education SaaS competitor snapshot",{"competitor":"Generic AI lesson planning tools","pricing":"Varied monthly subscriptions","launches":["AI-generated assessments","Teacher workflow assistants"]}),("market","Founder-observed market signals",{"trends":["Schools want shared teacher workflows rather than isolated accounts","AI tools must prove measurable time savings"],"pain_points":["Teachers pay but fail to reach first value","School decision-makers need a clear ROI demonstration"]})]
    for source_type,name,data in snapshots:knowledge_graph.ingest(workspace_id,source_type,name,data,product_id=product["id"])
    repo.create("support_tickets",workspace_id,{"customer_name":"Demo Teacher","customer_email":"teacher@example.com","subject":"I paid but do not know where to start","message":"My account is active, but I have not generated anything. Which workflow should I use first?","priority":"high","status":"open","assigned_agent":"support_agent","draft_status":"not_started"})
    return {"product":product,"sources_created":len(snapshots),"message":"BooxClash demo data loaded."}
