import { useId, useState } from "react";
type SignalName="Curiosity"|"Confusion"|"Suspicion"|"Emotional pull"|"Recall";
export type TimelineSignal={name:SignalName;values:number[];color:string};
const timestamps=["00:00","00:45","01:30","02:15","03:00","03:45"];
const sample:TimelineSignal[]=[
 {name:"Curiosity",values:[38,62,74,68,81,72],color:"#c7a45a"},{name:"Confusion",values:[12,20,64,33,28,18],color:"#d47b6e"},
 {name:"Suspicion",values:[8,34,48,70,76,90],color:"#8ba6c9"},{name:"Emotional pull",values:[28,45,52,73,67,88],color:"#af87b9"},{name:"Recall",values:[90,76,63,52,41,64],color:"#7fa98a"}
];
function points(values:number[]){return values.map((v,i)=>`${20+i*116},${90-v*.7}`).join(" ")}
export function Timeline(){const [selected,setSelected]=useState(2);const title=useId();return <section className="surface p-5 md:p-7" aria-labelledby={title}>
 <div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">Preview data</p><h2 id={title} className="font-display text-3xl m-0">Audience Mind Timeline</h2><p className="text-slate text-sm">Deterministic samples — not generated by Gemini or queried from ClickHouse.</p></div><span className="text-sm text-slate">Selected marker: {timestamps[selected]}</span></div>
 <div className="mt-6 grid lg:grid-cols-[minmax(620px,1fr)_260px] gap-5 overflow-hidden"><div className="overflow-x-auto" tabIndex={0} aria-label="Scrollable timeline preview"><div className="min-w-[620px]">
 {sample.map(signal=><div className="grid grid-cols-[110px_1fr] items-center mb-2" key={signal.name}><span className="text-xs text-slate">{signal.name}</span><svg viewBox="0 0 620 100" role="img" aria-label={`${signal.name} signal from ${signal.values[0]} to ${signal.values.at(-1)}`} className="w-full h-[64px]"><line x1="20" y1="90" x2="600" y2="90" stroke="#292d32"/><polyline points={points(signal.values)} fill="none" stroke={signal.color} strokeWidth="2"/>{signal.values.map((v,i)=><circle key={i} cx={20+i*116} cy={90-v*.7} r={i===selected?6:3} fill={signal.color}/>)}</svg></div>)}
 <div className="ml-[110px] flex justify-between text-[11px] text-slate">{timestamps.map((t,i)=><button key={t} onClick={()=>setSelected(i)} aria-pressed={selected===i} className="bg-transparent border-0 text-inherit cursor-pointer">{t}</button>)}</div></div></div>
 <aside className="border-l border-[#2d3035] pl-5" aria-live="polite"><p className="eyebrow">Placeholder evidence</p><h3 className="text-lg">Story signal at {timestamps[selected]}</h3><p className="text-sm text-slate leading-6">Future evidence will connect this moment to scenes, persona states, transcript cues and a traceable ClickHouse MCP query.</p><dl className="text-sm"><dt className="text-slate">Source</dt><dd className="ml-0 mb-3">Sample timeline fixture</dd><dt className="text-slate">Confidence</dt><dd className="ml-0">Not assessed</dd></dl></aside></div></section>}

